---
label: Site configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: description
  label: Site description
  description: The default site description used in meta data
- type: field_group
  name: header
  label: Header configuration
  fields:
  - type: include
    name: include_header
    label: Header configuration
    template: header
- type: field_group
  name: footer
  label: Footer configuration
  fields:
  - type: include
    name: include_footer
    label: Footer configuration
    template: footer
pages:
- site-metadata.json
